---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: show hostname
    ios_command:
      commands: show running-config | include hostname
    register: hostname
  
  - debug: msg="{{ hostname.stdout}}"
  
  - name: Config hostname
     ios_config:
       lines: hostname {{ new_hostname }}