---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:

  - name: show hostname
    ios_command:
      commands: show running-config | include hostname

   - name: change hostname
     ios_config:
       lines: hostname {{ new_hostname }}