---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:

  - name: show old hostname
    ios_command:
      commands: show running-config | include hostname
    register: old_host
    
  - name: configure top level configuration
    ios_config:
      lines: hostname {{ new_hostname }}

  - name: show new hostname
    ios_command:
      commands: show running-config | include hostname
    register: new_host
    
  - debug: 
     - old="{{ old_host.stdout}}"
     - new="{{ new_host.stdout}}"